name: sequana_variant_calling

channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - freebayes>1.3
  - bwa
  - bcftools
  - 'snpeff==5.1d'
  - sambamba
  - fastp
  - fastqc
  - picard>2.26
  - samtools>=1.15
  - bamtools
  - minimap2
  - pip
  - pip:
    - "sequana>=0.19.4"


